### ISSUE TITLE
Change Discord Videos from NHL URL to mp4 link for embedded videos

### ISSUE THREAD

**Issue by RevelRob** [mattdonders/nhl-twitter-bot#30]
Video Highlight link is located in Content Feed at media.milestones.items[i].highlight.playbacks[9].url where "i" is specific milestone.

Recap is at media.epg[3].items[0].playbacks[9].url
Condensed Game is at media.epg[2].items[0].playbacks[9].url

**Comment by mattdonders** [comment]
Will roll this into some other Discord improvements I am making.

**Comment by mattdonders** [comment]
Done - ended up using videos that matched the `FLASH_1800K_896x504` name within the `playbacks` dictionary.
