### ISSUE TITLE
End-of-Period graphic has score reversed

### ISSUE THREAD

**Issue by holmesr19** [mattdonders/nhl-twitter-bot#32]
[Tweet](https://twitter.com/HurricanesBot/status/1288577073112592385) shows CAR 2 - WSH 1 in the graphic, but the score is CAR 1 - WSH 2. The scores appears to be correct elsewhere.

**Comment by mattdonders** [comment]
Fixed all stats image related bugs in commit fe968036870964a41c76b469dd21c9ef0104dbb9 (better late than never). 

Thanks for your report! 🚨
